In [13]:
import numpy as np
from multiprocessing import Pool

cloud = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

feature1_last = np.array([[1, 2], 
                          [7, 8],
                          [4, 5],
                          [4, 5]])

feature1 = np.array([[1, 2], 
                     [4, 5],
                     [2, 8],
                     [7, 5]])

feature2 = np.array([[10, 20],
                     [40, 50],
                     [70, 80]])

In [14]:
def get_row_index(row, matrix):
    assert len(row.shape) == 1 and len(matrix.shape) == 2 and row.shape[0] == matrix.shape[1]

    for i in range(matrix.shape[0]):
        if np.array_equal(row, matrix[i, :]):
            return i
    return None


def get_rows_index(matrix1, matrix2):
    assert len(matrix1.shape) == 2 and len(matrix2.shape) == 2 and matrix1.shape[1] == matrix2.shape[1]
    
    index = []
    # for i in range(matrix1.shape[0]):
    #     index.append(get_row_index(matrix1[i, :], matrix2))

    with Pool() as p:  # 创建多个进程
        results = [p.apply_async(get_row_index, args=(matrix1[i, :], matrix2)) for i in range(matrix1.shape[0])]
        # 获取所有进程返回的结果
        index = [result.get() for result in results]
    return index

In [15]:
built_index = get_rows_index(feature1, feature1_last)
print(built_index)

[0, 2, None, None]


In [6]:
built_index = list(filter(lambda x: x is not None, built_index))
cloud[built_index]

array([[1, 2, 3],
       [7, 8, 9]])

In [7]:
feature2[built_index]

array([[10, 20],
       [70, 80]])

In [9]:
mask = np.array([True, False, True])
feature2[mask]

array([[10, 20],
       [70, 80]])