In [1]:
import numpy as np
from multiprocessing import Pool

cloud = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

feature1_last = np.array([[1, 2], 
                          [7, 8],
                          [4, 5],
                          [4, 5]])

feature1 = np.array([[1, 2], 
                     [4, 5],
                     [2, 8],
                     [7, 5]])

feature2 = np.array([[10, 20],
                     [40, 50],
                     [70, 80]])

In [2]:
def get_row_index(row, matrix):
    assert len(row.shape) == 1 and len(matrix.shape) == 2 and row.shape[0] == matrix.shape[1]

    for i in range(matrix.shape[0]):
        if np.array_equal(row, matrix[i, :]):
            return i
    return None


def get_rows_index(matrix1, matrix2):
    assert len(matrix1.shape) == 2 and len(matrix2.shape) == 2 and matrix1.shape[1] == matrix2.shape[1]
    
    index = []
    # for i in range(matrix1.shape[0]):
    #     index.append(get_row_index(matrix1[i, :], matrix2))

    with Pool() as p:  # 创建多个进程
        results = [p.apply_async(get_row_index, args=(matrix1[i, :], matrix2)) for i in range(matrix1.shape[0])]
        # 获取所有进程返回的结果
        index = [result.get() for result in results]
    return index

In [3]:
# built_index = get_rows_index(feature1, feature1_last)
# print(built_index)

In [4]:
# built_index = list(filter(lambda x: x is not None, built_index))
# cloud[built_index]

In [5]:
# feature2[built_index]

In [6]:
mask = np.array([True, False, True])
feature2[mask]

array([[10, 20],
       [70, 80]])

In [7]:
import numpy as np
from math import sqrt

# 3x4转移矩阵
T = np.array([[1, 0, 0, 2],
              [0, 1, 0, 3],
              [0, 0, 1, 4]])

# T = np.array([[0, -1, 0, 2],
#               [1, 0, 0, 3],
#               [0, 0, 1, 4]])

T = np.array([[1, 0, 0, 2],
              [0, 0, 1, 3],
              [0, -1, 0, 4]])
# 计算平移量
t = T[:3, 3]
print(t)

# 计算四元数
R = T[:3, :3]
q0 = sqrt(1 + R[0][0] + R[1][1] + R[2][2]) / 2
q1 = (R[2][1] - R[1][2]) / (4*q0)
q2 = (R[0][2] - R[2][0]) / (4*q0)
q3 = (R[1][0] - R[0][1]) / (4*q0)
q = np.array([q1, q2, q3, q0])

pose = np.hstack([t, q])
print(pose)

[2 3 4]
[ 2.          3.          4.         -0.70710678  0.          0.
  0.70710678]


In [8]:
try:
    import torch
    from dpviewer import Viewer
except ModuleNotFoundError as e:
    use_dpviewer = False
    print("Error:", e)

Error: No module named 'dpviewer'


In [9]:
mask = np.array([True, False, True, False])
print(np.where(mask))
print(feature1)
[feature1[i] for i in np.where(mask)[0]]

(array([0, 2], dtype=int64),)
[[1 2]
 [4 5]
 [2 8]
 [7 5]]


[array([1, 2]), array([2, 8])]

In [10]:
cloud = np.array([[1, 2, 3],
                    [4, 5, 6], 
                    [7, 8, 9]])

index = [0,2]
cloud[index]

array([[1, 2, 3],
       [7, 8, 9]])

In [12]:
a = np.array([1,2,4,3,7,5])
b = np.array([5,3,7])
np.where(a == b[0])

(array([5], dtype=int64),)